// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    entry: {
      zombies: './src/zombies.js'
    },
    output: {
      path: './dist',
      filename: 'zombies.js'
    },
    resolve: {
      extension: ['', '.js']
    }
  };

}).call(this);

//# sourceMappingURL=webpack.config.js.map
