// Generated by CoffeeScript 1.8.0
(function() {
  var arrayPush;

  arrayPush = function(arr, fn) {
    [].concat(fn).forEach(function(fn) {
      return arr.push(fn);
    });
    return arr;
  };

  module.exports = {
    arrayPush: arrayPush
  };

}).call(this);

//# sourceMappingURL=array.js.map
