// Generated by CoffeeScript 1.8.0
(function() {
  var arrayPush, branch, getBranch, isArray, isBranch;

  isArray = require('./utils').isArray;

  arrayPush = require('./array').arrayPush;

  isBranch = isArray;

  getBranch = function(arr) {
    var last, newBranch;
    last = arr[arr.length - 1];
    if (isBranch(last)) {
      return last;
    } else {
      newBranch = [];
      arr.push(newBranch);
      return newBranch;
    }
  };


  /*
  new a fn branch
   */

  branch = function(obj, curring, fnStack) {
    obj.branch = obj.b = function(fnArr) {
      var branchFnStack;
      branch = getBranch(fnStack);
      branchFnStack = [];
      arrayPush(branch, [branchFnStack]);
      arrayPush(branchFnStack, fnArr);
      return function(_startArg, _endArg) {
        return curring(_startArg, _endArg, branchFnStack);
      };
    };
    return obj;
  };

  module.exports = {
    isBranch: isBranch,
    getBranch: getBranch,
    branch: branch
  };

}).call(this);

//# sourceMappingURL=branch.js.map
