// Generated by CoffeeScript 1.8.0
(function() {
  var isAboutFn, isArray;

  isAboutFn = function(arg) {
    return typeof arg === 'function' || arg.every && arg.every(function(fn) {
      return typeof fn === 'function';
    });
  };

  isArray = function(arg) {
    return Array.isArray(arg);
  };

  module.exports = {
    isAboutFn: isAboutFn,
    isArray: isArray
  };

}).call(this);

//# sourceMappingURL=utils.js.map
